<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexora.Business\Nexora.Business.csproj" />
    <ProjectReference Include="..\Nexora.Data\Nexora.Data.csproj" />
    <ProjectReference Include="..\Nexora.Integrations\Nexora.Integrations.csproj" />
  </ItemGroup>

</Project>
