<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nexora.Business\Nexora.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

</Project>
